export const airportsCity: { [key: string]: string } = {
  'LIS': 'Lisboa',
  'WAS': 'Washington, D.C.',
  'PAR': 'Paris',
  'SEL': 'Seul',
  'MAD': 'Madri',
  'HND': 'Tóquio',
  'CHI': 'Chicago',
  'LAX': 'Los Angeles',
  'ORL': 'Orlando',
  'NYC': 'Nova York',
  'MIL': 'Milão',
  'BUE': 'Buenos Aires',
  'LON': 'Londres',
  'MIA': 'Miami',
  'IAH': 'Houston',
  'LIM': 'Lima',
  'JFK': 'Nova York',
  'GIG': 'Rio de Janeiro',
  'FOR': 'Fortaleza',
  'NAT': 'Natal',
  'SAO': 'São Paulo',
  'REC': 'Recife',
  'MCZ': 'Maceió',
  'RIO': 'Rio de Janeiro',
  'CNF': 'Belo Horizonte',
  'BSB': 'Brasília',
  'AJU': 'Aracaju',
  'GRU': 'São Paulo',
  'ATL': 'Atlanta',
  'PEK': 'Pequim',
  'DXB': 'Dubai',
  'ORD': 'Chicago',
  'LHR': 'Londres',
  'PVG': 'Xangai',
  'CDG': 'Paris',
  'DFW': 'Dallas',
  'CGH': 'São Paulo',
  'SDU': 'Rio de Janeiro',
  'POA': 'Porto Alegre',
  'SSA': 'Salvador',
  'CWB': 'Curitiba',
  'BEL': 'Belém',
  'MAO': 'Manaus',
  'VIX': 'Vitória',
  'AMS': 'Amsterdã',
  'FRA': 'Frankfurt',
  'IST': 'Istambul',
  'SIN': 'Singapura',
  'ICN': 'Incheon',
  'BKK': 'Bangkok',
  'HKG': 'Hong Kong',
  'EZE': 'Buenos Aires',
  'MXP': 'Milão',
  'ORY': 'Paris',
  'AUH': 'Abu Dhabi',
  'LAS': 'Las Vegas',
  'YYZ': 'Toronto',
  'YUL': 'Montreal'
};


export const continentsTranslate: { [key: string]: string } = {
  'South America': 'América do Sul',
  'North America': 'América do Norte',
  'Europe': 'Europa',
  'Asia': 'Asia',
  'Africa': 'África',
  'Oceania': 'Oceanía'
};

export const brasilAeroportos: string[] = [
  "GRU",
  "GIG",
  "BSB",
  "CGH",
  "SDU",
  "VCP",
  "POA",
  "CNF",
  "REC",
  "SSA",
  "FOR",
  "CWB",
  "FLN",
  "MAO",
  "NAT",
  "BEL",
  "MCZ",
  "SLZ",
  "CGB",
  "AJU",
  "VIX",
  "JPA",
  "IGU",
  "STM",
  "TFF",
  "THE",
  "MCP",
  "BVB",
  "PVH",
  "RBR",
  "PPB",
  "UDI",
  "LDB",
  "MGF",
  "SJP",
  "VDC",
  "IOS",
  "CPV",
  "RAO",
  "CAW",
  "XAP",
];
